FROM flink:1.18-scala_2.12

USER root

RUN mkdir -p /state-backend \
 && chown flink:flink /state-backend

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python3.10 python3-venv python3-pip python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

USER flink